name: Visual Regression Test
on: deployment_status
jobs:
  build:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Percy Test
        run: |
          npm install
          npx percy exec -- node test/snapshots.js
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          DEPLOY_URL: ${{ github.event.deployment_status.target_url }}
