name: Visual Regression Test
on: deployment_status
jobs:
  build:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Install
        run: npm install
      - name: Percy Test
        uses: percy/exec-action@v0.3.0
        with:
          command: "node test/snapshots.js"
          verbose: true
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          DEPLOY_URL: ${{ github.event.deployment_status.target_url }}
